server {
    listen 8080;
    server_name _;
    root /app/public;
    index index.php;

    client_max_body_size 20m;

    location ^~ /storage/ {
        try_files $uri =404;
        access_log off;
        add_header Cache-Control "public, max-age=86400" always;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
